import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/modules/header/components/header";
import LoginDialog from "@/modules/auth/components/login/dialog";
import { ThemeProvider } from "@/modules/theme/components/provider";
import Footer from "@/modules/footer/components/footer";
import AuthProvider from "@/modules/auth/components/provider";
import { Provider as JotaiProvider } from "jotai";
import { Toaster } from "@/modules/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NEXTV - Movie Application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <JotaiProvider>
          <AuthProvider>
            <ThemeProvider>
              <Header />
              <LoginDialog />
              {children}
              <Footer />
              <Toaster />
            </ThemeProvider>
          </AuthProvider>
        </JotaiProvider>
      </body>
    </html>
  );
}
